import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { CookieConsent } from '@/components/CookieConsent';

export default function TermsOfService() {
    const navigate = useNavigate();

    return (
        <div className="min-h-screen bg-gradient-hero">
            <Header />
            <div className="container max-w-3xl mx-auto pt-32 pb-12 px-4 md:pt-40">
                <Button variant="ghost" className="mb-8" onClick={() => navigate('/')}>
                    <ArrowLeft className="mr-2 h-4 w-4" />
                    Back to Home
                </Button>

                <article className="prose prose-lg dark:prose-invert max-w-none">
                    <h1 className="font-display font-bold mb-2">Terms of Service</h1>
                    <p className="text-muted-foreground text-sm mb-8">Last Updated: {new Date().toLocaleDateString()}</p>

                    <h2>1. Acceptance of Terms</h2>
                    <p>
                        By accessing and using Humanizer AI (the "Service"), you agree to be bound by these Terms of Service.
                        If you do not agree, strictly do not use the Service.
                    </p>

                    <h2>2. Use License</h2>
                    <p>
                        We grant you a limited, non-exclusive, non-transferable license to use the Service for personal and commercial purposes, subject to these Terms.
                    </p>
                    <p><strong>You agree NOT to use the Service to:</strong></p>
                    <ul>
                        <li>Engage in academic dishonesty, plagiarism, or cheating.</li>
                        <li>Generate spam, misleading content, or misinformation.</li>
                        <li>Attempt to bypass our rate limits, security measures, or reverse engineer our API.</li>
                    </ul>

                    <h2>3. Service Limitations</h2>
                    <p>
                        <strong>"As Is" Basis:</strong> The Service is provided "as is" without warranties of any kind.
                        While we strive for high-quality "humanization," we do not guarantee that the output will bypass all AI detectors
                        or be free from errors. AI detection is a probabilistic field, and results may vary.
                    </p>
                    <p>
                        <strong>Rate Limits:</strong> Free usage is subject to "Token Bucket" rate limiting to prevent abuse.
                        We reserve the right to modify these limits at any time.
                    </p>

                    <h2>4. Intellectual Property</h2>
                    <p>
                        You retain all rights to the original text you input and the humanized text output generated by the Service.
                        We claim no ownership over your content.
                    </p>

                    <h2>5. Termination</h2>
                    <p>
                        We reserve the right to terminate or suspend your access to the Service immediately, without prior notice,
                        for any reason, including breach of these Terms.
                    </p>

                    <h2>6. Limitation of Liability</h2>
                    <p>
                        In no event shall Humanizer AI be liable for any indirect, incidental, or consequential damages arising
                        out of your use of the Service, including but not limited to academic penalties, loss of data, or business interruption.
                    </p>

                    <h2>7. Changes to Terms</h2>
                    <p>
                        We may modify these Terms at any time. Continued use of the Service constitutes acceptance of the modified Terms.
                    </p>
                </article>
            </div>
            <Footer />
            <CookieConsent />
        </div>
    );
}
